//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektDM_13185
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkersEntities : DbContext
    {
        public WorkersEntities()
            : base("name=WorkersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dni_urlopowe> Dni_urlopowe { get; set; }
        public virtual DbSet<Dzial> Dzial { get; set; }
        public virtual DbSet<Kraj_pochodzenia> Kraj_pochodzenia { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
    }
}
