//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektDM_13185
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public int id { get; set; }
        public int dzial_id { get; set; }
        public int kraj_id { get; set; }
        public int urlop_id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string PESEL { get; set; }
        public string nr_tel { get; set; }
    
        public virtual Dni_urlopowe Dni_urlopowe { get; set; }
        public virtual Dzial Dzial { get; set; }
        public virtual Kraj_pochodzenia Kraj_pochodzenia { get; set; }
    }
}
